# Standard Libraries
from typing import (
    Any,
    Callable,
    List,
    Optional,
    Type,
)

# Third Party Libraries
from ghidra.app.plugin import ProgramPlugin
from ghidra.framework.model import (
    DomainFile,
    DomainObject,
)
from ghidra.framework.options import SaveState
from ghidra.framework.plugintool import (
    Plugin,
    PluginEvent,
    PluginTool,
)
from ghidra.program.model.listing import Program
from ghidra.program.util import (
    ProgramLocation,
    ProgramSelection,
)

class DecafPlugin(Plugin):
    def __init__(self, tool: PluginTool) -> None: ...
    def getSupportedDataTypes(self) -> Optional[List[Type[Any]]]: ...
    def acceptData(self, data: List[DomainFile]) -> bool: ...
    def accept(self, url: Any) -> bool: ...  # java.net.URL
    def getData(self) -> Optional[List[DomainFile]]: ...
    def dispose(self) -> None: ...
    def processEvent(self, event: PluginEvent) -> None: ...
    def readConfigState(self, saveState: SaveState) -> None: ...
    def writeConfigState(self, saveState: SaveState) -> None: ...
    def writeDataState(self, saveState: SaveState) -> None: ...
    def readDataState(self, saveState: SaveState) -> None: ...
    def serviceAdded(self, interfaceClass: Type[Any], service: Any) -> None: ...
    def serviceRemoved(self, interfaceClass: Type[Any], service: Any) -> None: ...
    def canClose(self) -> bool: ...
    def canCloseDomainObject(self, dObj: DomainObject) -> bool: ...
    def prepareToSave(self, dObj: DomainObject) -> None: ...
    def saveData(self) -> bool: ...
    def hasUnsaveData(self) -> bool: ...
    def close(self) -> None: ...
    def restoreTransientState(self, state: Any) -> None: ...
    def getTransientState(self) -> Any: ...
    def dataStateRestoreCompleted(self) -> None: ...
    def getUndoRedoState(self, domainObject: DomainObject) -> Any: ...
    def restoreUndoRedoState(self, domainObject: DomainObject, state: Any) -> None: ...

class DecafProgramPlugin(ProgramPlugin):
    def __init__(self, tool: PluginTool) -> None: ...
    def getSupportedDataTypes(self) -> Optional[List[Type[Any]]]: ...
    def acceptData(self, data: List[DomainFile]) -> bool: ...
    def accept(self, url: Any) -> bool: ...
    def getData(self) -> Optional[List[DomainFile]]: ...
    def dispose(self) -> None: ...
    def processEvent(self, event: PluginEvent) -> None: ...
    def readConfigState(self, saveState: SaveState) -> None: ...
    def writeConfigState(self, saveState: SaveState) -> None: ...
    def writeDataState(self, saveState: SaveState) -> None: ...
    def readDataState(self, saveState: SaveState) -> None: ...
    def serviceAdded(self, interfaceClass: Type[Any], service: Any) -> None: ...
    def serviceRemoved(self, interfaceClass: Type[Any], service: Any) -> None: ...
    def canClose(self) -> bool: ...
    def canCloseDomainObject(self, dObj: DomainObject) -> bool: ...
    def prepareToSave(self, dObj: DomainObject) -> None: ...
    def saveData(self) -> bool: ...
    def hasUnsaveData(self) -> bool: ...
    def close(self) -> None: ...
    def restoreTransientState(self, state: Any) -> None: ...
    def getTransientState(self) -> Any: ...
    def dataStateRestoreCompleted(self) -> None: ...
    def getUndoRedoState(self, domainObject: DomainObject) -> Any: ...
    def restoreUndoRedoState(self, domainObject: DomainObject, state: Any) -> None: ...
    def programActivated(self, program: Program) -> None: ...
    def postProgramActivated(self, program: Program) -> None: ...
    def programClosed(self, program: Program) -> None: ...
    def programOpened(self, program: Program) -> None: ...
    def programDeactivated(self, program: Program) -> None: ...
    def locationChanged(self, loc: Optional[ProgramLocation]) -> None: ...
    def selectionChanged(self, sel: Optional[ProgramSelection]) -> None: ...
    def highlightChanged(self, hl: Optional[ProgramSelection]) -> None: ...

class PyGhidraDecafPlugin(DecafPlugin):
    def __init__(self, tool: PluginTool): ...
    def setInitializer(
        self, init_handler: Callable[[PyGhidraDecafPlugin], None]
    ) -> None: ...
    def init(self) -> None: ...
